services:

  appDb:
    image: bitnami/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yogakeroh14
      MYSQL_DATABASE: myproject
    ports: 
      - 80:80
    healthcheck:
      test: ["CMD", "mysql", "-u", "root",  "-pyogakeroh14", "-e", "show schemas"]
      interval: 10s 

  app:
    build: .
    restart: always
    depends_on:
      appDb:
        condition: service_healthy
    environment:
      HTTP_PORT: 80
      CONNECTION_STRING: root:yogakeroh14@tcp(appDb:3306)/alta?charset=utf8&parseTime=True&loc=Local
      STORAGE: db
    ports:
      - 80:80

  adminer:
    image: adminer
    restart: always
    ports: # host:container
      - 8081:8080